version: '2'

services:
  backend:
    build:
      dockerfile: ./docker/dockerfile.prod
    extends:
      file: ./docker-compose.base.yml
      service: backend
    image: app:prod
    container_name: ${APP_NAME}
    environment:
      NODE_ENV: "production"
    entrypoint: ["npm", "start"]

  nginx:
    extends:
      file: ./docker-compose.base.yml
      service: nginx
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"
